services:
  web:
    build:
      context: ./web/
    env_file:
      - /web/.env
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    expose:
      - 5432

volumes:
  db-data:


